# Generated by Django 5.0.1 on 2024-01-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file1',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='file',
            name='file2',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
