# Generated by Django 5.0.1 on 2024-01-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_client_remove_file_name_file_file12_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_name',
            new_name='name',
        ),
    ]
