# Generated by Django 5.0.1 on 2024-01-21 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_rename_file_name_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uploads.client'),
            preserve_default=False,
        ),
    ]
