# Generated by Django 5.0.1 on 2024-01-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_file_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file12_name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file1_name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file2',
        ),
    ]
