# Generated by Django 5.0.1 on 2024-01-21 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_remove_file_file1_remove_file_file12_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_pic',
            field=models.FileField(blank=True, default='profile_pics/default.jpg', upload_to='profile_imgs/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='uploads.client'),
        ),
    ]
