# Generated by Django 5.0.1 on 2024-01-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_client_profile_pic_alter_file_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_pic',
            field=models.FileField(blank=True, default='profile_pics/default.png', upload_to='profile_imgs/'),
        ),
    ]
