# Generated by Django 5.0.1 on 2024-01-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_alter_client_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_pic',
            field=models.FileField(blank=True, default='profile_imgs/default.png', upload_to='profile_imgs/'),
        ),
    ]
