# Generated by Django 5.0.1 on 2024-01-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0010_alter_client_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='veh_reg',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
